# Generated by Django 6.0.5 on 2026-05-30 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Party_Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('whatsapp_number', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product_Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('size_max', models.IntegerField()),
                ('size_min', models.IntegerField()),
                ('packing', models.CharField(choices=[('loose', 'Loose'), ('box', 'Box'), ('china', 'China Packing')], max_length=50)),
                ('opening_balance', models.IntegerField(blank=True, null=True)),
                ('color', models.ManyToManyField(blank=True, to='Order_Dashboard.color')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('size_max', models.IntegerField()),
                ('size_min', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('packing', models.CharField(choices=[('loose', 'Loose'), ('box', 'Box'), ('china', 'China Packing')], max_length=50)),
                ('color', models.ManyToManyField(blank=True, to='Order_Dashboard.color')),
            ],
        ),
        migrations.CreateModel(
            name='Sub_Party_Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('transport', models.CharField(max_length=50)),
                ('marka', models.CharField(max_length=50)),
                ('station', models.CharField(max_length=50)),
                ('parent_party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Order_Dashboard.party_master')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('transport', models.CharField(max_length=50)),
                ('marka', models.CharField(max_length=50)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Order_Dashboard.party_master')),
                ('product_order', models.ManyToManyField(to='Order_Dashboard.OrderItem')),
                ('sub_party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Order_Dashboard.sub_party_master')),
            ],
        ),
    ]
