# Generated by Django 6.0.5 on 2026-05-31 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order_Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='product_order',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Order_Dashboard.orders'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='party_master',
            name='marka',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='party_master',
            name='station',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='party_master',
            name='transport',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='party_master',
            name='whatsapp_number',
            field=models.CharField(default=12345678, max_length=15),
            preserve_default=False,
        ),
    ]
