# Generated by Django 6.0.5 on 2026-06-02 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order_Dashboard', '0004_remove_orderitem_name_orderitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_party_master',
            name='parent_party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_parties', to='Order_Dashboard.party_master'),
        ),
    ]
